language: elixir
elixir:
  - 1.7
  - 1.8
otp_release:
  - 21.0
sudo: false

before_install:
- sudo apt-get update -qq
- sudo apt-get install -q -y fdk-aac

script:
  - mix format --check-formatted
  - mix test
