version: 2.0
jobs:
  build:
    docker:
      - image: membrane/elixir-fdk-aac:1.0.0
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test
